package ch.ex17.access;

/**
 * Created by V1 on 16.03.2017.
 */
public enum WaterColors {
    ZINC, LEM0N_YELL0W, MEDIUM_YELLOW, DEEP_YELL0W, ORANGE,
    BRILLIANT_RED, CRIMSON, MAGENTA, ROSE_MADDER, VIOLET,
    CERULEAN_BLUE_HUE, PHTHALO_BLUE, ULTRAMARINE,
    C0BALT_BLUE_HUE, PERMANENT_GREEN, VIRIDIAN_HUE,
    SAP_GREEN, YELL0W_OCHRE, BURNT_SIENNA, RAW_UMBER,
    BURNT_UMBER, PAYNES_GRAY, IVORY_BLACK
}
